# Development Setup for performing E2E tests on Neptune
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: sem_elasticsearch
    restart: on-failure
    environment: 
      - "discovery.type=single-node"
    ports: 
      - 9200:9200
    networks: 
      - nep-test-network
  logstash:
    image: studysnap/logstash-pg-es:1.x
    container_name: sem_logstash
    restart: on-failure
    environment:
      LS_HOST: "0.0.0.0"
      DB_HOST: notedb
      DB_PORT: 5432
      DB_USER: studysnap
      DB_PASS: snapstudy
      DB_NAME: studysnap_notedb
      ES_HOST: elasticsearch
      ES_PORT: 9200
    volumes:
      - "./.docker/es-search/config:/usr/share/logstash/config"
      - "./.docker/es-search/pipelines:/usr/share/logstash/pipeline"
    depends_on: 
      - notedb
      - elasticsearch
    networks: 
      - nep-test-network
  notedb:
    image: postgres:13.1
    container_name: studysnap_testdb
    restart: on-failure
    environment:
      POSTGRES_DB: studysnap_testdb
      POSTGRES_USER: studysnap
      POSTGRES_PASSWORD: snapstudy
    ports:
      - 8888:5432
    networks:
      - nep-test-network
  classdb:
    image: postgres:13.1
    container_name: studysnap_classdb
    restart: on-failure
    environment:
      POSTGRES_DB: studysnap_classdb
      POSTGRES_USER: studysnap
      POSTGRES_PASSWORD: snapstudy
    networks:
      - nep-test-network
  authentication:
    image: studysnap/authentication:1.x
    container_name: authentication
    restart: on-failure
    environment:
      PORT: 5555
      DB_USER: studysnap
      DB_PASS: snapstudy
      DB_HOST: classdb
      DB_USER_DATABASE: studysnap_classdb
      JWT_SECRET: test
      JWT_ACCESS_TOKEN_EXPIRE_TIME: 999m
    depends_on:
      - classdb
    ports:
      - 5555:5555
    networks:
      - nep-test-network

networks:
  nep-test-network:
    driver: bridge