# Development Setup for working on Neptune
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: sem_elasticsearch
    restart: on-failure
    environment: 
      - "discovery.type=single-node"
    ports: 
      - 9200:9200
    networks: 
      - nep-dev-network
  es_sidecar:
    image: bash:latest
    container_name: es_sidecar
    restart: on-failure
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
    command: bash -c "/util/config-scripts/elastic-customizer.sh"
    volumes:
      - "./.docker/es-search/scripts/:/util/config-scripts/"
    depends_on:
      - elasticsearch
    networks:
      - nep-dev-network
  logstash:
    image: studysnap/logstash-pg-es:1.x
    container_name: sem_logstash
    restart: on-failure
    environment:
      LS_HOST: "0.0.0.0"
      DB_HOST: ssdb
      DB_PORT: 5432
      DB_USER: studysnap
      DB_PASS: snapstudy
      DB_NAME: studysnap_db
      ES_HOST: elasticsearch
      ES_PORT: 9200
    volumes:
      - "./.docker/es-search/config:/usr/share/logstash/config"
      - "./.docker/es-search/pipelines:/usr/share/logstash/pipeline"
    depends_on: 
      - ssdb
      - elasticsearch
    networks: 
      - nep-dev-network
  ssdb:
    image: postgres:13.1
    container_name: studysnap_db
    restart: on-failure
    environment:
      POSTGRES_DB: studysnap_db
      POSTGRES_USER: studysnap
      POSTGRES_PASSWORD: snapstudy
    volumes:
      - ssdb_data:/var/lib/postgresql/data
    ports:
      - 8888:5432
    networks:
      - nep-dev-network
  authentication:
    image: studysnap/authentication:1.x
    container_name: authentication
    restart: on-failure
    environment:
      PORT: 5555
      DB_USER: studysnap
      DB_PASS: snapstudy
      DB_HOST: ssdb
      DB_USER_DATABASE: studysnap_db
      JWT_SECRET: dev
      JWT_ACCESS_TOKEN_EXPIRE_TIME: 999m
    depends_on:
      - ssdb
    ports:
      - 5555:5555
    networks:
      - nep-dev-network

networks:
  nep-dev-network:
    driver: bridge
volumes:
  ssdb_data: