export const PROJECT_VERSION = '0.0.1'
export const SEQUELIZE = 'SEQUELIZE'
export const DEVELOPMENT = 'development'
export const JWT_STRATEGY = 'jwt'
export const TEST = 'test'
export const PRODUCTION = 'production'
